# This workflow will run Waldo Unit Tests on pull request event to `main` branch

name: Waldo unit tests

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Run unit tests with tox
      run: |
        mkdir -p nblogs
        /nfs/site/disks/de_pdk_automation_disk001/shared/bin/tox -e gh_unittest -r
