# This workflow will run Waldo Unit Tests on pull request event to `main` branch

name: Waldo unit tests

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Run unit tests with tox
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install tox
        mkdir -p nblogs
        tox -e gh_unittest -r
